config/routes.rb
RememberMe::Application.routes.draw do

  scope "(:locale)", :locale => /#{Locales.available.keys.join('|')}/ do

    devise_for :users, :controllers => {:registrations => 'users/registrations' }, :path_names => { :sign_in => "log_in", :sign_out => "log_out", :sign_up => "create_account" } do
      get 'users/registrations/success', :to => 'users/registrations#success'
    end

    resources :schedules, :path => '/reminders' do
      resources :logs, :only => :index
      resources :subscribers, :only => [:index, :destroy]
    end

    match :receive_at, :controller => "nuntium", :action => :receive_at

    resources :channel, :only => [:create, :destroy]

    get "new_channel/:step", :action => :new, :controller => :channel, :as => "new_channel"

    get  'bulk_uploads', :action => :index,  :controller => :bulk_uploads, :as => "bulk_uploads"
    post 'bulk_uploads', :action => :upload, :controller => :bulk_uploads, :as => "bulk_uploads"

    match 'tour/:page' => 'tour#show', :as => :tour
    match 'tour' => 'tour#index'
    match 'help' => 'help#faq'
    match 'community' => 'community#index'

    get  'createAccount', :to => redirect('/%{locale}/users/create_account'), :defaults => { :locale => 'en' }
    get  'discuss',       :to => redirect(RememberMe::Application.config.user_group_url)
    get  'backlog',       :to => redirect(RememberMe::Application.config.backlog_url)

    match '/locale/update' => 'locale#update',  :as => 'update_locale'
    match '/' => 'home#index',                  :as => 'home'

  end

  root :to => 'home#index'

end

app/models/schedule.rb
# Copyright (C) 2011-2012, InSTEDD
# 
# This file is part of Remindem.
# 
# Remindem is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Remindem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Remindem.  If not, see <http://www.gnu.org/licenses/>.

class Schedule < ActiveRecord::Base
  validates_presence_of :keyword, :user_id, :welcome_message, :type, :title
  validates_presence_of :timescale, :unless => Proc.new {|schedule| schedule.type == "CalendarBasedSchedule"}
  validates_uniqueness_of :keyword
  validates_length_of :keyword, :maximum => 15
  validates_format_of :keyword, :with => /^[^ ]+$/, :message => "must not include spaces"
  validates_length_of :title, :maximum => 60
  belongs_to :user

  has_many :messages, :dependent => :destroy
  has_many :subscribers, :dependent => :destroy
  has_many :logs, :dependent => :destroy

  accepts_nested_attributes_for :messages, :allow_destroy => true
  validates_associated :messages
  before_validation :initialize_messages

  before_destroy :notify_deletion_to_subscribers
  before_update :log_changes

  attr_accessor_with_default :notifySubscribers, true

  def keyword_is_not_opt_out_keyword
    if keyword && self.class.is_opt_out_keyword?(keyword)
      errors.add(:keyword, "Must not be \"#{self.class.opt_out_keyword}\" as it will be used for subscribers to unsubscribe.")
    end
  end

  validate :keyword_is_not_opt_out_keyword

  def self.inherited(child)
    # force all subclass to have :schedule as model name
    child.instance_eval do
      def model_name
        Schedule.model_name
      end
    end
    super
  end

  def subscribe subscriber
    generate_reminders_for subscriber
    log_new_subscription_of subscriber.phone_number
    welcome_message_for subscriber.phone_number
  end

  def generate_reminders_for recipient
    messages = self.reminders

    messages.each_with_index do |message, index|
      self.enqueue_reminder message, index, recipient
    end
  end

  def welcome_message_for phone_number
    [build_message(phone_number, welcome_message)]
  end

  def self.time_scale_options
    [[_('Minutes'), 'minutes'], [_('Hours'), 'hours'], [_('Days'), 'days'], [_('Weeks'), 'weeks'], [_('Months'), 'months'], [_('Years'), 'years']]
  end

  def build_message to, body
    self.user.build_message to, body
  end

  def send_or_reschedule message, subscriber
    if !paused?
      if subscriber.can_receive_message
        send_message subscriber.phone_number, message.text
      else
        #TODO-LOW build a better estimate for when to reschedule, although thanks to the
        # timewindow restriction, this will be pushed many times until it is able to go out
        try_to_send_it_at = Time.now.utc + 1.hour
        schedule_message message, subscriber, try_to_send_it_at
        create_warning_log_described_by "The message '#{message.text}' was delayed due to #{subscriber.phone_number.without_protocol} localtime"
      end
    else
      create_warning_log_described_by "The message '#{message.text}' was not sent to #{subscriber.phone_number.without_protocol} since schedule is paused"
    end
  end

  def schedule_message message, subscriber, send_at
    Delayed::Job.enqueue ReminderJob.new(subscriber.id, self.id, message.id),
      :message_id => message.id, :subscriber_id => subscriber.id, :run_at => send_at
  end

  def last_job_for subscriber
    Delayed::Job.order('run_at DESC').where(:subscriber_id => subscriber.id).first
  end

  def send_message to, body
    nuntium = Nuntium.new_from_config
    message = self.build_message to, body
    nuntium.send_ao message
    log_message_sent body, to
  end

  def log_message_sent body, recipient_number
    create_information_log_described_by (_("The message '%{body}' was sent to %{recipient}") % {body: body, recipient: recipient_number.without_protocol})
  end

  def log_new_subscription_of recipient_number
    create_information_log_described_by (_("New subscriber: %{subscriber}") % {subscriber: recipient_number.without_protocol})
  end

  def create_warning_log_described_by description
    Log.create! :schedule => self, :severity => :warning, :description => description
  end

  def create_information_log_described_by description
    Log.create! :schedule => self, :severity => :information, :description => description
  end

  def log_message_updated message
    create_information_log_described_by _("Message updated: %{message}") % {message: message.text}
  end

  def log_message_deleted message
    create_information_log_described_by _("Message deleted: %{message}") % {message: message.text}
  end

  def log_message_created message
    create_information_log_described_by _("Message created: %{message}") % {message: message.text}
  end

  def initialize_messages
    messages.each { |m| m.schedule = self }
  end

  def notify_deletion_to_subscribers
    if notifySubscribers
      subscribers.each do |subscriber|
        self.send_message(subscriber.phone_number,
          (_("The schedule %{keyword} has been deleted. You will no longer receive messages from this schedule.") % {keyword: self.keyword}))
      end
    end
  end

  def log_changes
    log_if_welcome_message_changed
    log_if_paused_or_resumed
  end

  def log_if_welcome_message_changed
    if welcome_message_changed?
      log_welcome_message_updated
    end
  end

   def log_welcome_message_updated
    create_information_log_described_by (_("Welcome message has been updated: %{message}") % {message: welcome_message})
  end

  def log_if_paused_or_resumed
    if paused_changed?
      if paused?
        log_schedule_paused
      else
        log_schedule_resumed
      end
    end
  end

  def log_schedule_paused
    create_information_log_described_by _("Schedule paused")
  end

  def log_schedule_resumed
    create_information_log_described_by _("Schedule resumed")
  end

  def mode_in_words
    raise NotImplementedError, 'Subclasses must redefine this message'
  end

  def self.is_opt_out_keyword? keyword
    keyword.upcase == opt_out_keyword.upcase
  end

  def self.opt_out_keyword
    'stop'
  end

  def duration
    raise NotImplementedError, 'Subclasses must redefine this message'
  end

end

app/controllers/schedules_controller.rb
# Copyright (C) 2011-2012, InSTEDD
#
# This file is part of Remindem.
#
# Remindem is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Remindem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Remindem.  If not, see <http://www.gnu.org/licenses/>.

class SchedulesController < AuthenticatedController

  def initialize
    super
    @show_breadcrumb = true
    add_breadcrumb _("Reminders"), :schedules_path
  end

  # GET /schedules
  # GET /schedules.xml
  def index
    @at_least_one_schedule_is_paused = !Schedule.where(:user_id => current_user.id, :paused => true).empty?

    @schedules = if params[:show] == 'all' || params[:show].nil?
        Schedule.where(:user_id => current_user.id)
      else
        Schedule.where(:user_id => current_user.id, :paused => params[:show] == 'paused')
      end

    @last_log = Log.find(:all, :conditions => ["schedule_id in (?)", @schedules.collect(&:id)]).sort_by(&:created_at).reverse.first rescue nil
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.xml
  def show
    @schedule = Schedule.find(params[:id])
    add_breadcrumb @schedule.title, schedule_path(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.xml
  def new
    add_breadcrumb _("New Reminder"), :new_schedule_path
    @schedule = FixedSchedule.new :timescale => "hours"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
    add_breadcrumb @schedule.title, schedule_path(params[:id])
    add_breadcrumb _("Settings"), edit_schedule_path(params[:id])
    @schedule.sort_messages
  end

  # POST /schedules
  # POST /schedules.xml
  def create
    params[:schedule][:user] = current_user
    @schedule = params[:schedule][:type].constantize.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to(schedule_url(@schedule), :notice => _('Schedule was successfully created.')) }
        format.xml  { render :xml => @schedule, :status => :created, :location => @schedule }
      else
        add_breadcrumb _("New Reminder"), :new_schedule_path
        format.html { render :action => "new" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.xml
  def update
    @schedule = Schedule.find(params[:id])

    #Type needs to be manually set because it's protected, thus update_attributes doesn't affect it
    @schedule.type = params[:schedule][:type] unless params[:schedule][:type].blank?

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to(schedule_url(@schedule), :notice => _('Schedule was successfully updated.')) }
        format.xml  { head :ok }
      else
        add_breadcrumb @schedule.title, schedule_path(params[:id])
        add_breadcrumb _("Settings"), edit_schedule_path(params[:id])

        format.html { render :action => "edit" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.xml
  def destroy
    @schedule = Schedule.find(params[:id])
    if params[:notify] == "true"
      @schedule.notifySubscribers = true
    else
      @schedule.notifySubscribers = false
    end
    @schedule.destroy

   respond_to do |format|
     format.html { redirect_to(schedules_url, :notice => _('Schedule was successfully deleted.')) }
     format.xml  { head :ok }
   end
  end
end

app/helpers/schedules_helper.rb
# Copyright (C) 2011-2012, InSTEDD
# 
# This file is part of Remindem.
# 
# Remindem is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Remindem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Remindem.  If not, see <http://www.gnu.org/licenses/>.

module SchedulesHelper
  def setup_schedule(schedule)
    schedule.tap do |s|
      s.messages.build if s.messages.empty?
    end
  end
end

app/views/schedules/_form.html.haml
- content_for :head do
  = javascript_include_tag 'schedules'
= form_for @schedule, :validate => true do |f|
  = errors_for @schedule, :as => :reminder
  .field.w60
    = f.label :titleapp, _("Title")
    = f.text_field :title, :class => "causesPendingSaveNoticeOnChange"
  .field.w60
    = f.label :keyword, _("Keyword")
    %p Users will register with this keyword
    = f.text_field :keyword, :class => "causesPendingSaveNoticeOnChange"
  .field
    = f.label :welcome_message, _("Welcome message")
    %p This is the message users will get after they successfully registered
    .w60
      = f.text_area :welcome_message,                          |
        :rows => 3,                                            |
        :class => "causesPendingSaveNoticeOnChange ux-wajbar", |
        :placeholder => _('Write your welcome message here'),  |
        :maxlength => 160                                      |
  .field
    = f.label :timescale, _("Timescale")
    %p Choose timescale reference to use
    .ux-dropdown.w20.inline
      = f.select :timescale, Schedule.time_scale_options, {}, :class => "causesPendingSaveNoticeOnChange"
  .field
    %label Mode
    %p
      = _("Choose whether you want to set up a timeline for your messages or send them randomly")
      = _("(Only available if there are no subscribers)") unless @schedule.subscribers.empty?
    = f.radio_button :type,                               |
      "FixedSchedule",                                    |
      :id => "fixed_schedule_option",                     |
      :class => "causesPendingSaveNoticeOnChange styled", |
      :disabled => !@schedule.subscribers.empty?          |

    = f.label :type, FixedSchedule.mode_in_words, :class => 'radio'
    %br/
    = f.radio_button :type,                               |
      "RandomSchedule",                                   |
      :id => "random_schedule_option",                    |
      :class => "causesPendingSaveNoticeOnChange styled", |
      :disabled => !@schedule.subscribers.empty?,         |
      'data-message' => _("Random Once")                  |
    = f.label :type, RandomSchedule.mode_in_words, :class => 'radio'
  %hr/
  %h2 Messages
  %p Write your reminder's messages
  %ul.vertical
    = f.fields_for :messages, :validate => false do |message_form|
      = render "message_fields", :f => message_form
    %li.fields
      .box.grey.w60.reminderMessageBox
        = link_to_add_fields _("Add message"), f, :messages, :class => "add_fields causesPendingSaveNoticeOnClick"
        %button.cadd.right{:onclick => "$('.add_fields', $(this).closest('.box')).click();", :type => "button"}
  %hr/
  .actions
    %button.white{:type => "submit"} Save
    = link_to _('Cancel'), :back

app/views/schedules/_message_add.html.haml
= render "message_fields", :f => f
= render "message_controls", :f => f, :save_onclick => 'confirm_add(this);', :cancel_onclick => 'revert_add(this);'

app/views/schedules/_message_controls.html.haml
- save_onclick ||= 'confirm_changes(this);'
- cancel_onclick ||= 'revert_changes(this);'
%li.fields
  .box.w60.reminderMessageBox
    = link_to_remove_fields '', f, :class => "fdelete causesPendingSaveNoticeOnClick"
    .offset.left
      .ux-nstep
        = tag :input, :name => "edit_offset", :size => "2", :type => "text", :value => f.object.offset, :onblur => "validate_onblur(this);", :'data-min' => "0"
      %span.timescale= @schedule.timescale
    .text
      = content_tag :textarea, f.object.text, :rows => 4, :class => "ux-wajbar w60", :placeholder => _('Add message here'), |
        :name => "edit_text" , :maxlength => 160, :onblur => "validate_onblur(this);"                                    |
    %hr/
    .actions
      %button.white{:onclick => "return #{save_onclick}", :type => "button"} Save
      %a{:href => "#", :onclick => "#{cancel_onclick}; return false;"} Cancel

app/views/schedules/_message_fields.html.haml
%li.fields
  = errors_for f.object, :as => :message
  .box.grey.w60.reminderMessageBox.closed
    = link_to_remove_fields '', f, :class => "fdelete causesPendingSaveNoticeOnClick"
    .left.offset
      = f.hidden_field :offset, :class => "offset"
      After
      %span.offset= f.object.offset
      %span.timescale= @schedule.timescale
    = f.hidden_field :text, :class => "hidden text"
    %pre.aleft.text.w55= f.object.text
    %span.aleft
      = link_to_edit_fields "Edit", f, :messages
    .clear

app/views/schedules/edit.html.haml
= render "shared/schedule_tabs_and_title", :schedule => @schedule
.tabsline
  %h2 Properties
  %p Below you can configure this Reminder properties
  = render 'form'

app/views/schedules/index.html.haml
- content_for :head do
  :javascript
    $(function() {
      $('.ItemsTable tr').live('click', function() {
        var anchor = $('a', $(this));
        if (anchor.length > 0) {
          window.location = anchor.attr('href');
        }
      });

      $(".filterSchedules").change(function () {
        $(".filterSchedules option:selected").each(function () {
          window.location = $(this).val();
        });
      });
    })

%h1 Reminders
.tablewrapp.RemindersTable
  %table{:class => "GralTable TwoColumn CleanTable ItemsTable #{'empty' if @schedules.empty?}"}
    %tr
      %th My Reminders
      %th
        = content_tag :select, :class => 'filterSchedules', :disabled => !@at_least_one_schedule_is_paused do
          = options_for_select([                                                                                  |
              [_('Show All'),'all'],                                                                              |
              [_('Paused'),'paused'],                                                                             |
              [_('Running'),'running']                                                                            |
            ].map { |text,show| [text, schedules_path(:show => show)] }, schedules_path(:show => params[:show]) ) |
    - if @schedules.empty?
      %tr
        %td{:colspan => "2"}
          .EmptyRemindersTable
            - if params[:show] == 'running'
              You have no running Reminders
            - else
              You have no Reminders yet
            %br/
            = link_to _('Create Reminder'), new_schedule_path, :class => 'EmptyAddLink'
            = link_to '', new_schedule_path, :class => 'EmptyAddButton button cadd'
    - else
      - @schedules.each do |schedule|
        %tr
          %td{:class => schedule.paused? ? 'spaused' : 'sactive'}
            %span
            = link_to schedule_path(schedule) do
              = schedule.title
              .indexKeyword
                \&#x2192;
                = schedule.keyword
          %td= link_to '', schedule_path(schedule), :class => 'farrow'
      %tr
        %td
          = link_to _('Create Reminder'), new_schedule_path
        %td
          = link_button_to '', new_schedule_path, :class => 'cadd'

- if current_user.feature_enabled?(:bulk_upload)
  %p= link_to _("Subscribers bulk upload"), bulk_uploads_path, :class => 'farrow'

= render :partial => 'channel/user_channel'

app/views/schedules/new.html.haml
%h1 New reminder
= render 'form'

app/views/schedules/show.html.haml
- content_for :head do
  :javascript
    function updateNotifyValue(){
    	if ($('#notifySubscribers:checked').val() !== undefined) {
    		send_notification = true;
    	}else {
    		send_notification = false;
    	}
    	$('#delete').attr('href', ($('#delete').attr('href').replace("NOTIFY_VALUE", send_notification)));
    };
= render "shared/schedule_tabs_and_title", :schedule => @schedule
.tabsline
  %h2 Status
  %p Here you can see the overall status of your schedule
  = render 'subscribers/download_as_csv', :schedule => @schedule
  %hr/
  %h2 Properties
  %p This is a summary of the properties of your schedule
  .left.box.plain.white.overviewBox
    .i48grad-key.left
    .overviewText
      Keyword
      %br/
      = @schedule.keyword
  .left.box.plain.white.overviewBox
    .i48grad-time.left
    .overviewText
      = "#{@schedule.duration} #{@schedule.timescale}"
      %br/
      = @schedule.class.mode_in_words
  .left.box.plain.white.overviewBox
    .i48grad-reminder.left
    .overviewText
      = @schedule.messages.count
      messages
      %br>/
      queued
  .clear
  = link_to _('Edit settings'), edit_schedule_path(@schedule), :class => 'farrow overviewButton'
  = form_for(@schedule) do |f|
    %p.pausedDescription
      - if @schedule.paused?
        = _("This Reminder is paused and won't send messages.")
      - else
        = _("This Reminder is active and will be sending messages to registered users.")
    = f.hidden_field :paused?, :value => !@schedule.paused?
    - if @schedule.paused?
      %button.fplay.overviewButton{:type => "submit"} Start this reminder
    - else
      %button.fpause.overviewButton{:type => "submit"} Pause this reminder
  %hr/
  .ux-collapsible.collapsed.deleteScheduleBox.switch{"data-on-expanded" => "box grey plain expanded"}
    %span
      %a.icon.fdelete.ux-collapse-trigger.black{:href => "#"} Delete this reminder
    .ux-content
      %a.icon.fdelete.ux-collapse-trigger{:href => "#"}
        Are you sure you want to delete this reminder?
        %br/
        All your subscribers will stop receiving the scheduled messages
      %hr/
      %input#notifySubscribers{:checked => "", :name => "notifySubscribers", :type => "checkbox"}/
      = label_tag :notifySubscribers, "Notify the subscribers that this reminder is no longer active?"
      = link_to 'Confirm', schedule_path(@schedule, :notify => "NOTIFY_VALUE"), :method => :delete , :class => "button white right", :id => "delete", :onclick => "updateNotifyValue();"
      %a.ux-collapse-trigger.grey.right{:href => "#"} Cancel