config/routes.rb
RememberMe::Application.routes.draw do

  scope "(:locale)", :locale => /#{Locales.available.keys.join('|')}/ do

    devise_for :users, :controllers => {:registrations => 'users/registrations' }, :path_names => { :sign_in => "log_in", :sign_out => "log_out", :sign_up => "create_account" } do
      get 'users/registrations/success', :to => 'users/registrations#success'
    end

    resources :schedules, :path => '/reminders' do
      resources :logs, :only => :index
      resources :subscribers, :only => [:index, :destroy]
    end

    match :receive_at, :controller => "nuntium", :action => :receive_at

    resources :channel, :only => [:create, :destroy]

    get "new_channel/:step", :action => :new, :controller => :channel, :as => "new_channel"

    get  'bulk_uploads', :action => :index,  :controller => :bulk_uploads, :as => "bulk_uploads"
    post 'bulk_uploads', :action => :upload, :controller => :bulk_uploads, :as => "bulk_uploads"

    match 'tour/:page' => 'tour#show', :as => :tour
    match 'tour' => 'tour#index'
    match 'help' => 'help#faq'
    match 'community' => 'community#index'

    get  'createAccount', :to => redirect('/%{locale}/users/create_account'), :defaults => { :locale => 'en' }
    get  'discuss',       :to => redirect(RememberMe::Application.config.user_group_url)
    get  'backlog',       :to => redirect(RememberMe::Application.config.backlog_url)

    match '/locale/update' => 'locale#update',  :as => 'update_locale'
    match '/' => 'home#index',                  :as => 'home'

  end

  root :to => 'home#index'

end

app/views/shared/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '#{RememberMe::Application.config.google_analytics}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_langs.haml
- if Locales.many? && controller.controller_name == 'home'
  .right.homepage
    %ul.language
      - Locales.available.each do |key,name|
        %li{:class => ('selected' if I18n.locale == key)}
          %a{:href => '#', 'data-lang' => key}
            = name

app/views/shared/_langs_menu.haml
%span.lang-menu
  %ul.language{:style => "height: #{20 * Locales.available.count + 15}px"}
    - Locales.available.each do |key,name|
      %li
        %a{:href => '#', 'data-lang' => key}
          = name
  %span
    Language:
    = Locales.available[I18n.locale]

app/views/shared/_schedule_tabs_and_title.html.haml
%h1= schedule.title
%ul.tabs.top
  %li{:class => ("active" if (params[:controller] == "schedules" && params[:action] == "show"))}
    = link_to _("Overview"), schedule_path(schedule.id)
  %li{:class => ("active" if params[:controller] == "logs")}
    = link_to _("Logs"), schedule_logs_path(schedule.id)
  %li{:class => ("active" if(params[:controller] == "schedules" && (params[:action] == "edit" || params[:action] == "update")))}
    = link_to _("Settings"), edit_schedule_path(schedule.id)
  %li{:class => ("active" if params[:controller] == "subscribers")}
    = link_to _("Subscribers"), schedule_subscribers_path(schedule.id)