config/routes.rb
RememberMe::Application.routes.draw do

  scope "(:locale)", :locale => /#{Locales.available.keys.join('|')}/ do

    devise_for :users, :controllers => {:registrations => 'users/registrations' }, :path_names => { :sign_in => "log_in", :sign_out => "log_out", :sign_up => "create_account" } do
      get 'users/registrations/success', :to => 'users/registrations#success'
    end

    resources :schedules, :path => '/reminders' do
      resources :logs, :only => :index
      resources :subscribers, :only => [:index, :destroy]
    end

    match :receive_at, :controller => "nuntium", :action => :receive_at

    resources :channel, :only => [:create, :destroy]

    get "new_channel/:step", :action => :new, :controller => :channel, :as => "new_channel"

    get  'bulk_uploads', :action => :index,  :controller => :bulk_uploads, :as => "bulk_uploads"
    post 'bulk_uploads', :action => :upload, :controller => :bulk_uploads, :as => "bulk_uploads"

    match 'tour/:page' => 'tour#show', :as => :tour
    match 'tour' => 'tour#index'
    match 'help' => 'help#faq'
    match 'community' => 'community#index'

    get  'createAccount', :to => redirect('/%{locale}/users/create_account'), :defaults => { :locale => 'en' }
    get  'discuss',       :to => redirect(RememberMe::Application.config.user_group_url)
    get  'backlog',       :to => redirect(RememberMe::Application.config.backlog_url)

    match '/locale/update' => 'locale#update',  :as => 'update_locale'
    match '/' => 'home#index',                  :as => 'home'

  end

  root :to => 'home#index'

end

app/models/channel.rb
# Copyright (C) 2011-2012, InSTEDD
# 
# This file is part of Remindem.
# 
# Remindem is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Remindem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Remindem.  If not, see <http://www.gnu.org/licenses/>.

class Channel < ActiveRecord::Base
  belongs_to :user
  before_destroy :remove_channel_from_nuntium
  
  def remove_channel_from_nuntium
    Nuntium.new_from_config.delete_channel name
  end
  
end

app/controllers/channel_controller.rb
# Copyright (C) 2011-2012, InSTEDD
# 
# This file is part of Remindem.
# 
# Remindem is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Remindem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Remindem.  If not, see <http://www.gnu.org/licenses/>.

class ChannelController < AuthenticatedController

  def new
  end

  def create
    unless params[:show_local_gateway]
      @channel = current_user.register_channel params[:channel][:code]
      params[:step] = "end_wizard"
      render :action => "new"
    end
  rescue Nuntium::Exception => exception
    @invalid_channel = Channel.new
    load_errors_from exception
    params[:step] = params[:channel][:step]
    render :action => "new"
  end   
   
   # DELETE /channels/1
   # DELETE /channels/1.xml
   def destroy
     @channel = Channel.find(params[:id])
     @channel.destroy

     respond_to do |format|
       format.html { redirect_to(schedules_url, :notice => _('Channel was successfully deleted.')) }
       format.xml  { head :ok }
     end
  rescue Nuntium::Exception => exception
    load_errors_from exception
    params[:step] = "user_channel"
    render :action => "new"
  end
  
  def load_errors_from exception
    if exception.properties.empty?
      @invalid_channel.errors.add(_('Unexpected Error: '), "\"#{exception.message}\"")
    end
    exception.properties.map do |value, msg|
      @invalid_channel.errors.add(("#{value.humanize}: "), msg)
    end
  end
  
end

app/helpers/channels_helper.rb
# Copyright (C) 2011-2012, InSTEDD
# 
# This file is part of Remindem.
# 
# Remindem is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Remindem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Remindem.  If not, see <http://www.gnu.org/licenses/>.

module ChannelsHelper
end

app/views/channel/_choose_local_gateway.html.haml
:javascript
  function updateLocalGatewaySelectionPath(){
  	if ($('input[name=localGateway]:radio:checked').val() == 'android') {
  		gateway = 'download_android_local_gateway';
  	} else {
  		gateway = 'download_desktop_local_gateway';
  	}
  	$('#next').attr('href', ($('#next').attr('href').replace("download_local_gateway", gateway)));
  };
.box.plain.grey.wizardSteps
  .steps-line
    .steps-container.s4
      %span.circle.first.green
        %span.inner
          %span.step-name Choose
      %span.line-fill
      %span.circle
        %span.inner
          %span.step-name Install
      %span.line-fill
      %span.circle
        %span.inner
          %span.step-name Connect
      %span.line-fill
      %span.circle.last
        %span.inner
          %span.step-name Finish
    / #steps-container
  / #steps-line
/ #box plain grey
.ChannelWizard
  %h1 Choose your type of mobile phone
  %input#androidLocalGateway.left{:checked => "", :name => "localGateway", :type => "radio", :value => "android"}/
  .left.AndroidLogo
  = label_tag :androidLocalGateway, _("Android mobile phone") , :class => "left"
  %p.w30.clear.description If you have an Android powered mobile phone, you don't need a computer to set up your schedules. Just download the application, enter your text messages, and set your delivery schedule, Remindem handles the rest.
  %input#desktopLocalGateway.left{:name => "localGateway", :type => "radio", :value => "desktop"}/
  .left.DesktopLogo
  = label_tag :desktopLocalGateway, _("Other mobile phone"), :class => "left"
  %p.w30.clear.description If you use another type of mobile phone all you need to do is plug your phone into your computer and bridge the gap between your text messages and the internet application that sends them out.
%hr/
.ChannelWizardNavigation
  = link_to _('Back'), schedules_path, :class => 'button white'
  = link_to _('Next'), new_channel_path(:download_local_gateway), :remote => true, :class => 'button grey', :onclick => "updateLocalGatewaySelectionPath();", :id => "next"

app/views/channel/_download_android_local_gateway.html.haml
.box.plain.grey.wizardSteps
  .steps-line
    .steps-container.s4
      %span.circle.first.green
        %span.inner
          %span.step-name Choose
      %span.line-fill.green
      %span.circle.green
        %span.inner
          %span.step-name Install
      %span.line-fill
      %span.circle
        %span.inner
          %span.step-name Connect
      %span.line-fill
      %span.circle.last
        %span.inner
          %span.step-name Finish
    / #steps-container
  / #steps-line
/ #box plain grey
.ChannelWizard
  %h1.orange Go to Android Market and install Nuntium Local Gateway
  %p.w30.grey
    Use the following QR code to access the app or use the search engine with the keyword
    %span.box.plain.grey Nuntium
  %br/
  .AndroidQR
  %br/
  %a{:href => "http://market.android.com/details?id=org.instedd.geochat.lgw", :target => "_blank"} http://market.android.com/details?id=org.instedd.geochat.lgw
  %br/
  %br/
%hr/
.ChannelWizardNavigation
  = link_to _('Back'), new_channel_path(:choose_local_gateway), :remote => true, :class => 'button white'
  = link_to _('Next'), new_channel_path(:new_android_channel), :remote => true, :class => 'button grey'

app/views/channel/_download_desktop_local_gateway.html.haml
.box.plain.grey.wizardSteps
  .steps-line
    .steps-container.s4
      %span.circle.first.green
        %span.inner
          %span.step-name Choose
      %span.line-fill.green
      %span.circle.green
        %span.inner
          %span.step-name Install
      %span.line-fill
      %span.circle
        %span.inner
          %span.step-name Connect
      %span.line-fill
      %span.circle.last
        %span.inner
          %span.step-name Finish
    / #steps-container
  / #steps-line
/ #box plain grey
.ChannelWizard
  %h1.orange Donwload and install Nuntium Local Gateway
  %p.w30 Nuntium Local Gateway is a program that runs on your local computer and requires a mobile phone to be plugged in. The Gateway will use the plugged-in phone for sending and receiving text messsages.
  %p.w30 Download the client corresponding to your operating system and install it.
  %a.fimport{:href => "https://bitbucket.org/instedd/local-gateway/downloads", :target => "_blank"} Download Nuntium Local Gateway
%hr/
.ChannelWizardNavigation
  = link_to _('Back'), new_channel_path(:choose_local_gateway), :remote => true, :class => 'button white'
  = link_to _('Next'), new_channel_path(:new_desktop_channel), :remote => true, :class => 'button grey'

app/views/channel/_end_wizard.html.haml
.box.plain.grey.wizardSteps
  .steps-line
    .steps-container.s4
      %span.circle.first.green
        %span.inner
          %span.step-name Choose
      %span.line-fill.green
      %span.circle.green
        %span.inner
          %span.step-name Install
      %span.line-fill.green
      %span.circle.green
        %span.inner
          %span.step-name Connect
      %span.line-fill.green
      %span.circle.last.green
        %span.inner
          %span.step-name Finish
    / #steps-container
  / #steps-line
/ #box plain grey
.ChannelWizard
  %h1 Congratulations! you have successfully created a channel
  %p.w30 The phone you have configured will be used for sending and receiving text messages. Ensure the phone is running and has credit for sending messages.
  .ChannelConfigured
%hr/
.ChannelWizardNavigation
  = link_to _('Finish'), schedules_path, :class => 'button white'

app/views/channel/_new_android_channel.html.haml
.box.plain.grey.wizardSteps
  .steps-line
    .steps-container.s4
      %span.circle.first.green
        %span.inner
          %span.step-name Choose
      %span.line-fill.green
      %span.circle.green
        %span.inner
          %span.step-name Install
      %span.line-fill.green
      %span.circle.green
        %span.inner
          %span.step-name Connect
      %span.line-fill
      %span.circle.last
        %span.inner
          %span.step-name Finish
    / #steps-container
  / #steps-line
/ #box plain grey
= errors_for @invalid_channel
- form_for :channel, :url => { :action => :create }, :remote => true do |f|
  .ChannelWizard
    = f.hidden_field :step, :value => "new_android_channel"
    %h1.orange Enter the gateway code from your mobile phone
    .AndroidScreen.left
    %br/
    .GreyArrow.AndroidArrow.left
    %br/
    .left.AndroidChannelCreation
      %p.w30 Copy the code for automated setup from the Nuntium Local Gateway in here to bind your local gateway to your reminders.
      = f.text_field :code, :placeholder => _('Enter gateway code'), :size => 19
  %hr/
  .ChannelWizardNavigation
    = link_to _('Back'), new_channel_path(:download_android_local_gateway), :remote => true, :class => 'button white'
    %button.grey{:type => "submit"} Next

app/views/channel/_new_desktop_channel.html.haml
.box.plain.grey.wizardSteps
  .steps-line
    .steps-container.s4
      %span.circle.first.green
        %span.inner
          %span.step-name Choose
      %span.line-fill.green
      %span.circle.green
        %span.inner
          %span.step-name Install
      %span.line-fill.green
      %span.circle.green
        %span.inner
          %span.step-name Connect
      %span.line-fill
      %span.circle.last
        %span.inner
          %span.step-name Finish
    / #steps-container
  / #steps-line
/ #box plain grey
= errors_for @invalid_channel
- form_for :channel, :url => { :action => :create }, :remote => true do |f|
  .ChannelWizard
    = f.hidden_field :step, :value => "new_desktop_channel"
    %h1.orange Enter the gateway code from your mobile phone
    .DesktopScreen.left
    %br/
    .GreyArrow.DesktopArrow.left
    %br/
    .left.DesktopChannelCreation
      %p.w30 Copy the code for automated setup from the Nuntium Local Gateway in here to bind your local gateway to your reminders.
      = f.text_field :code, :placeholder => _('Enter gateway code'), :size => 19
  %hr/
  .ChannelWizardNavigation
    = link_to _('Back'), new_channel_path(:download_desktop_local_gateway), :remote => true, :class => 'button white'
    %button.grey{:type => "submit"} Next

app/views/channel/_no_channel.html.haml
.LocalGatewayBox.box.plain.white
  .LocalGatewayLogo.left
  .LocalGatewayText.left
    will help you to send reminders from your mobile phone, 
    = link_to _('learn More'), tour_path(:start)
    = "."
  = link_to _('Add a channel'), new_channel_path(:choose_local_gateway), :remote => true, :class => 'button orange right'
  .LocalGatewayArrow.right

app/views/channel/_show_current_channel.html.haml
.CurrentChannelBox.box.grey
  .left
    %p.black Reminders channel
    %p.grey
      Bidirectional (#{current_user.channel.address.strip})
      - if @last_log
        , last activity #{time_ago_in_words @last_log.created_at} ago
  = link_to '', channel_path(current_user.channel), :method => :delete, :class => 'icon fdelete right'
.LocalGatewayBox.box.plain.white
  .LocalGatewayLogo.left
  .LocalGatewayText.left
    will help you to send reminders from your mobile phone, #{link_to _('learn More'), tour_path(:start)}.
  = link_to _('Change channel'), new_channel_path(:choose_local_gateway), :remote => true, :class => 'button white right'
  .LocalGatewayArrow.right

app/views/channel/_user_channel.html.haml
= errors_for @invalid_channel
.user_channel
  - if current_user.channel.nil?
    = render :partial => 'channel/no_channel'
  - else
    = render :partial => 'channel/show_current_channel'

app/views/channel/new.html.haml
= render :partial => params[:step]

app/views/channel/new.js.erb
$('.user_channel').html("<%= escape_javascript(render(:partial => params[:step]))%>")

app/views/channel/show.html.haml
= render :partial => 'user_channel'