config/routes.rb
RememberMe::Application.routes.draw do

  scope "(:locale)", :locale => /#{Locales.available.keys.join('|')}/ do

    devise_for :users, :controllers => {:registrations => 'users/registrations' }, :path_names => { :sign_in => "log_in", :sign_out => "log_out", :sign_up => "create_account" } do
      get 'users/registrations/success', :to => 'users/registrations#success'
    end

    resources :schedules, :path => '/reminders' do
      resources :logs, :only => :index
      resources :subscribers, :only => [:index, :destroy]
    end

    match :receive_at, :controller => "nuntium", :action => :receive_at

    resources :channel, :only => [:create, :destroy]

    get "new_channel/:step", :action => :new, :controller => :channel, :as => "new_channel"

    get  'bulk_uploads', :action => :index,  :controller => :bulk_uploads, :as => "bulk_uploads"
    post 'bulk_uploads', :action => :upload, :controller => :bulk_uploads, :as => "bulk_uploads"

    match 'tour/:page' => 'tour#show', :as => :tour
    match 'tour' => 'tour#index'
    match 'help' => 'help#faq'
    match 'community' => 'community#index'

    get  'createAccount', :to => redirect('/%{locale}/users/create_account'), :defaults => { :locale => 'en' }
    get  'discuss',       :to => redirect(RememberMe::Application.config.user_group_url)
    get  'backlog',       :to => redirect(RememberMe::Application.config.backlog_url)

    match '/locale/update' => 'locale#update',  :as => 'update_locale'
    match '/' => 'home#index',                  :as => 'home'

  end

  root :to => 'home#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Remindem
    = stylesheet_link_tag 'http://theme.instedd.org/theme/stylesheets/theme.css'
    = stylesheet_link_tag '/stylesheets/remindem.css'
    = javascript_include_tag :defaults, "rails.validations"
    = javascript_include_tag 'http://theme.instedd.org/theme/javascripts/theme.js'
    = csrf_meta_tag
    = yield(:head)
    :javascript
      function capitalizedSingular(timescale) {
        return caseTimescale(timescale,"#{_('minutes')}", "#{_('hours')}", "#{_('days')}", "#{_('weeks')}", "#{_('months')}", "#{_('years')}", "");
      };
      function timescaleToOneString(timescale) {
        return caseTimescale(timescale, "#{_('a minute')}", "#{_('an hour')}", "#{_('a day')}", "#{_('a week')}", "#{_('a month')}", "#{_('a year')}", "");
      };
      var unsaved_changes = "#{_('There are unsaved changes in your schedule!')}"
      var cant_be_blank = "#{_('can\'t be blank')}"
      var cant_be_greater_than_max = "#{_('can\'t be greater than 2147483647')}"
      var cant_be_negative = "#{_('can\'t be negative')}"

    %link{:href => "/images/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}/
    = render :partial =>"shared/analytics"
  %body{:class => ((@body_class || []) << I18n.locale).join(' ')}
    = flash_message
    #wrapper
      #toolbar
        %ul#instedd-pulldown
        #NavMenu
          %ul
            = section _('Home'), root_path, :home
            = section _('Reminders'), schedules_path, :schedules, [:schedules, :subscribers, :logs] unless current_user.nil?
            = section _('Tour'), tour_path(:start), :tour
            = section _('Community'), community_path, :community
            = section _('Help'), help_path , :help
        %ul.RightMenu
          - if !current_user.nil?
            %li
              #User
                = current_user.email
                %br/
                %br/
                .container
                  %ul
                    %li= link_to _('Reminders'), schedules_path
                    %li= link_to _('Settings'), edit_user_registration_path
                  %hr/
                  %ul
                    %li
                      %a{:href => "mailto:support@instedd.org?subject=[remindem-bug]"} Report a bug
                    %li= link_to _("Log Out"), destroy_user_session_path
            %li
              = link_to '', edit_user_registration_path, :class => 'fsettings'
          - else
            %li
              = link_to _("Create account"), new_user_registration_path, :class => 'fedit'
            %li
              = link_to _("Log in"), new_user_session_path, :class => 'fuser'
      #header
        .left
          %a{:href => "/"}
            %img{:src => "http://theme.instedd.org/theme/images/header/logos/remindem.png"}/
        - if @show_breadcrumb
          .BreadCrumb
            = breadcrumb
        = render :partial => 'shared/langs'
        .clear
      #container
        = yield
      #footer-span
        #footer
          #footer-container
            %div
              .left.platform
                InSTEDD has created an evolving platform of free and open source technologies to support humanitarian causes. These tools can be used individually or as building blocks for larger solutions.
                %a{:href => _("http://instedd.org/technologies/")} Click here
                to learn more
              .right
                %a.more{:href => _("http://instedd.org/technologies/")} Learn more
                #instedd-footer{"data-app-name" => "remindem"}
              .clear
            %div
              .left
                %a{:href => "http://instedd.org"} &copy; 2011 InSTEDD
                %a{:href => "#TODO"} Terms and conditions
                %a{:href => "mailto:support@instedd.org?subject=[remindem]"} Contact us
              .right
                %a{:href => root_path} Home
                %a{:href => tour_path(:start)} Tour
                %a{:href => community_path} Community
                %a{:href => help_path} Help
                = render partial: 'shared/langs_menu'
                %span.VersionNumber
                  Version #{RememberMe::Application.config.version_name}
              .clear

app/views/layouts/mail.html.erb
<%= body do %>
	<%=  header do %>
		<img src="http://theme.instedd.org/theme/images/header/logos/remindem.png"/>
		<img src="http://theme.instedd.org/theme/images/header/shadow_small.png"/>
	<% end %>
	<%= content do %>
		<%= yield %>
	<% end %>
  <%= footer do %>
		<hr/>
		<p>
			Do you have questions or need help? Contact us at
			<%= link "mailto:support@instedd.org?subject=Remindem" do %>
				support@instedd.org
			<% end %>
		</p>
	<% end %>
<% end %>

app/views/layouts/mail.text.erb
Remindem
--------


<%= yield %>


---------
Do you have questions or need help? Contact us at support@instedd.org